// فایل: api/image.js

export default async function handler(req, res) {
  try {
    // ابتدا چک می‌کنیم که آیا اطلاعاتی ارسال شده یا نه
    if (req.method !== 'POST') {
      res.status(405).send('Method Not Allowed');
      return;
    }
    
    const memoryText = req.body?.untrustedData?.inputText || "No memory shared!";
    const imageUrl = `https://og.onceupon.gg/card?text=${encodeURIComponent(memoryText)}`;
    const shareUrl = `https://warpcast.com/~/compose?text=${encodeURIComponent("My 2025 memory generated by diaryapp!")}&embeds[]=${imageUrl}`;

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta property="fc:frame" content="vNext" />
          <meta property="fc:frame:image" content="${imageUrl}" />
          <meta property="fc:frame:button:1" content="Share" />
          <meta property="fc:frame:button:1:action" content="link" />
          <meta property="fc:frame:button:1:target" content="${shareUrl}" />
          <meta property="fc:frame:button:2" content="Mint (Soon)" />
          <meta property="fc:frame:button:2:action" content="link" />
          <meta property="fc:frame:button:2:target" content="https://base.org" />
        </head>
        <body>
            <h1>Image Generated!</h1>
        </body>
      </html>
    `;

    res.setHeader('Content-Type', 'text/html');
    res.status(200).send(html);

  } catch (error) {
    console.error(error);
    // در صورت بروز خطا، یک فریم خطا نمایش می‌دهیم
    const errorHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta property="fc:frame" content="vNext" />
          <meta property="fc:frame:image" content="https://i.imgur.com/K1J3f4u.png" />
          <meta property="fc:frame:button:1" content="Try Again" />
          <meta property="fc:frame:post_url" content="https://diaryapp-beta.vercel.app/api/frame" />
        </head>
      </html>
    `;
    res.status(500).send(errorHtml);
  }
}
